version: '3'

services:
  back-end:
    build: ./python
    volumes:
      - ./python:/usr/src/app
    ports:
      - 8081:80

  front-end:
    image: php:apache
    volumes:
      - ./html:/var/www/html
    ports:
      - 8080:80
    depends_on:
      - back-end

  db:
    build: ./mysql
    restart: always
    environment:
      MYSQL_DATABASE: "db"
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "3306:3306"